# Generated by Django 3.1.7 on 2021-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitingBills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
