# Generated by Django 3.1.7 on 2021-03-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SplitingBills', '0002_day_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='foodname',
            new_name='title',
        ),
    ]
