# Generated by Django 3.1.7 on 2021-03-18 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SplitingBills', '0004_auto_20210318_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='usedfood',
        ),
        migrations.AddField(
            model_name='food',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='SplitingBills.person'),
        ),
        migrations.AddField(
            model_name='food',
            name='usedday',
            field=models.ManyToManyField(to='SplitingBills.Day'),
        ),
    ]
