# Generated by Django 3.1.7 on 2021-03-19 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SplitingBills', '0005_auto_20210319_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(null=True, verbose_name='日付')),
                ('cost', models.IntegerField(verbose_name='価格')),
                ('meal_name', models.CharField(max_length=50, verbose_name='食材名')),
                ('participant', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参加者(複数)')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Meal_payer', to=settings.AUTH_USER_MODEL, verbose_name='購入者')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('is_Done', models.BooleanField(verbose_name='支払われたかどうか')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Money_borrower', to=settings.AUTH_USER_MODEL, verbose_name='借りた人')),
                ('lender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Money_lender', to=settings.AUTH_USER_MODEL, verbose_name='貸した人')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SplitingBills.meal', verbose_name='どの食材についてか')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='food',
            name='usedday',
        ),
        migrations.RemoveField(
            model_name='person',
            name='joined',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
